import { Avatar as DiceBearAvatar, Style } from "@dicebear/core";
import adventurerNeutral from "@dicebear/styles/adventurer-neutral.json" with { type: "json" };
import type { CSSProperties } from "react";

/*
 * C-282 BotFace — the face a new bot is given, drawn from a seed.
 *
 * Every face is DiceBear's Adventurer Neutral: eyes, brows and a mouth on a
 * solid ground, no head, no hair. It is a remix of Lisa Wischofsky's pack of
 * the same name (CC BY 4.0), and it is chosen because a bot is a colleague
 * rather than a user account — an expression, not a portrait — and because a
 * drawn pack with a named artist is what we want to be seen crediting.
 *
 * A face is a pure function of its seed. Nothing is fetched and nothing is
 * generated by a model: the style definition and the renderer are bundled, so
 * the same seed draws the same face offline, in a test, and on the host once
 * it has been painted and put on the bot.
 */

/** The one style this component draws, built once and reused for every face. */
const style = new Style(adventurerNeutral);

/**
 * Who drew the pack, read from the style definition itself rather than typed
 * in here, so a pack update carries its own credit. The artist's link is the
 * one the credit line opens; the pack's own page belongs to a fuller credits
 * screen.
 */
export const botFaceCredit = {
    pack: adventurerNeutral.meta.source.name,
    artist: adventurerNeutral.meta.creator.name,
    artistUrl: adventurerNeutral.meta.creator.url,
} as const;

/** The SVG markup for a seed, at the given pixel size. */
export function botFaceSvg(seed: string, size: number): string {
    return new DiceBearAvatar(style, { seed, size }).toString();
}

/** The face as a data URL, for an `<img>`. */
export function botFaceDataUri(seed: string): string {
    return new DiceBearAvatar(style, { seed }).toDataUri();
}

/** The raster the host keeps: 256px is more than any face is shown at. */
const PAINT_SIZE = 256;

/** A painted face, in the one encoding the host accepts from here. */
export interface BotFacePainting {
    readonly contentType: "image/png";
    readonly data: ArrayBuffer;
}

/**
 * Paints a seed's face as PNG bytes. The host stores raster pictures only, so
 * the SVG is decoded through an image element and drawn onto a canvas here,
 * in the one place that has both.
 */
export async function botFacePaint(seed: string): Promise<BotFacePainting> {
    const blob = new Blob([botFaceSvg(seed, PAINT_SIZE)], { type: "image/svg+xml" });
    const url = URL.createObjectURL(blob);
    try {
        const image = new Image(PAINT_SIZE, PAINT_SIZE);
        image.src = url;
        await image.decode();
        const canvas = document.createElement("canvas");
        canvas.width = PAINT_SIZE;
        canvas.height = PAINT_SIZE;
        const context = canvas.getContext("2d");
        if (!context) throw new Error("The face could not be painted.");
        context.drawImage(image, 0, 0, PAINT_SIZE, PAINT_SIZE);
        const png = await new Promise<Blob | null>((resolve) =>
            canvas.toBlob(resolve, "image/png"),
        );
        if (!png) throw new Error("The face could not be painted.");
        return { contentType: "image/png", data: await png.arrayBuffer() };
    } finally {
        URL.revokeObjectURL(url);
    }
}

export type BotFaceProps = {
    /** The seed the face is drawn from. */
    seed: string;
    /** The square the face fills, in pixels. */
    size: number;
    className?: string;
    "data-testid"?: string;
    style?: CSSProperties;
};

/** One face, as an image that is exactly its box. Decorative: the seed is not a name. */
export function BotFace(props: BotFaceProps) {
    return (
        <img
            alt=""
            className={["happy-bot-face", props.className].filter(Boolean).join(" ")}
            data-happy-desktop-ui="bot-face"
            data-testid={props["data-testid"]}
            draggable={false}
            height={props.size}
            src={botFaceDataUri(props.seed)}
            style={props.style}
            width={props.size}
        />
    );
}
